Update github actions e2e tests

diff --git a/.github/workflows/db-test.yml b/.github/workflows/db-test.yml
--- a/.github/workflows/db-test.yml
+++ b/.github/workflows/db-test.yml
@@ -54,7 +54,12 @@ jobs:
           echo "Test PostgSail version"
           psql -c "SELECT value FROM app_settings WHERE name = 'app.version';"
           echo "Test PostgSail Unit Test"
-          docker-compose -f docker-compose.dev.yml -f docker-compose.yml up tests
+          docker-compose -f docker-compose.dev.yml -f docker-compose.yml up --exit-code-from tests
+          if [ $? != 0 ];
+          then
+              echo "Error running db-tests"
+              exit 1
+          fi
       - name: Show the logs
         if: always()
         run: |
diff --git a/.github/workflows/frontend-test.yml b/.github/workflows/frontend-test.yml
--- a/.github/workflows/frontend-test.yml
+++ b/.github/workflows/frontend-test.yml
@@ -43,9 +43,15 @@ jobs:
           docker-compose up -d db && sleep 15 && docker-compose up -d api && sleep 5
           docker-compose ps -a
           echo "Test PostgSail Web Unit Test"
-          docker-compose up -d web && sleep 5
+          docker-compose up -d web_dev && sleep 60
           docker-compose ps -a
           curl http://localhost:8080/
+          docker-compose -f docker-compose.dev.yml -f docker-compose.yml up --exit-code-from web_tests
+          if [ $? != 0 ];
+          then
+              echo "Error running frontend-tests"
+              exit 1
+          fi
       - name: Show the logs
         if: always()
         run: |
